### ISSUE TITLE
怎么做到实时的语音合成

### ISSUE THREAD

**Issue by freecui** [begeekmyfriend/tacotron2#13]
能否告诉生成一句话的时候，你那边tacotron2 model 和waveRnn 的用时分别是多少吗

**Comment by begeekmyfriend** [comment]
tacotron2耗时几乎不计，WaveRNN实时比达到10:1

**Comment by freecui** [comment]
能解释一下 'WaveRNN实时比达到10:1' 吗？不是太理解你说的意思

**Comment by begeekmyfriend** [comment]
就是1分钟音频花费6秒钟合成

**Comment by freecui** [comment]
OK，谢谢。目前感觉wavernn耗时还是比较长的，有什么解决方案吗

**Comment by freecui** [comment]
’1分钟音频花费6秒钟合成‘是说的按照gpu的标准，还是cpu？

**Comment by begeekmyfriend** [comment]
我是GPU，所以你还可以用`TensorRT`，CPU就难了，其它效果都不如`WaveRNN`

**Comment by freecui** [comment]
好的，后面我去尝试一下；非常感谢

**Comment by begeekmyfriend** [comment]
Now [here](https://github.com/begeekmyfriend/SqueezeWave) is the new solution for real time synthesis. Please match it with the latest version of T2. FYI https://github.com/tianrengao/SqueezeWave/issues/4
```shell
nohup python train.py -c configs/config_a256_c256.json > checkpoint_a256_c256.out &
```

**Comment by agonzalezd** [comment]
This is interesting... Is it compatible with the output of this repository?

Do you plan to make a single repository with both the multispeaker spectrogram generation and the real time synthesis?

Thanks in advance!

**Comment by freecui** [comment]
Could you tell me the cuda and torch version?

**Comment by freecui** [comment]
could you tell me which is faster ,  tensorflow tacotron2 inference speed  and your pytorch tacotron2?  and How much faster

**Comment by begeekmyfriend** [comment]
The larger synthesized batch size, the faster the synthesis speed.

**Comment by freecui** [comment]
Is your cuda version 10.1?

**Comment by begeekmyfriend** [comment]
Of course.
