### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by agonzalezd** [begeekmyfriend/tacotron2#15]
Hello

I was checking your repository for using it with my own data, and I found that I couldn't create a docker image from the Dockerfile since the `requirements.txt` file is missing...

Could you provide it or say which are the needed requirements for it to work? I'm having issues with GPU drivers and I would like to check at least those that work for you.

Thank you so much for your response,

Ander

**Comment by begeekmyfriend** [comment]
Here is the commit https://github.com/begeekmyfriend/tacotron2/commit/8adb9accf0b4ecb56c821cd80719063706b6df0a
Since I do not use docker and I have no plan to install such environmennt recently, I am not sure whether it might work for you. Please let me know if you have any problem. Have fun!

**Comment by agonzalezd** [comment]
Yes, thank you!

I have to change some things due to hardware compatibility issues but it is a good starting point. Thanks!

**Comment by begeekmyfriend** [comment]
Here is a real time synthesiis solution for you https://github.com/begeekmyfriend/tacotron2/issues/13#issuecomment-599992425

**Comment by agonzalezd** [comment]
This is interesting... Is it compatible with the output of this repository?

Do you plan to make a single repository with both the multispeaker spectrogram generation and the real time synthesis?

Thanks in advance!

**Comment by begeekmyfriend** [comment]
This project supports multi-speaker. See `scripts/train_tacotron2.sh`. And then throw all the GTA mel spectrograms into vocoder for training.

**Comment by agonzalezd** [comment]
Yes, I know. I was referring more to the "real time synthesis" part :)
