### ISSUE TITLE
文本中的英文缩写转换语音

### ISSUE THREAD

**Issue by jamesMuWB** [begeekmyfriend/tacotron2#18]
一段包含英文缩写的文本，在转成语音时英文缩写的部分会被跳过或者转成不能听的音频

有什么好办法能提升英文缩写转换的效果么

**Comment by begeekmyfriend** [comment]
Of course you need some corpus for training: https://github.com/Kyubyong/g2p

**Comment by jamesMuWB** [comment]
deep voice3是用cmudict把语料中的句子转成Phoneme训练的吧

试了[deepvoice3_pytorch](https://github.com/r9y9/deepvoice3_pytorch)这个项目（用LJSpeech模型），效果听上去没有什么提升

把replace_pronunciation_prob改成1.0，训练的模型，也没啥用

是我操作上有什么问题么

**Comment by begeekmyfriend** [comment]
没用过deepvoice3，个人没必要（你用也无妨），用这个配合README中的声码器效果已经可以了https://github.com/begeekmyfriend/tacotron2/issues/1

**Comment by jamesMuWB** [comment]
找到办法了，把replace_pronunciation_prob改成1.0训练的模型，在合成的时候也用replace_pronunciation_prob=1.0就能合成缩写的语音了

不知道咋上传附件。。

合成效果还可以，哈哈
