### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by nmfisher** [begeekmyfriend/tacotron2#2]
First off - great work! 

Second - will you make any pretrained models available? There are a few scattered throughout various issues in Rayhane's repository, but they all seem to be out of date and incompatible with the current master.

**Comment by begeekmyfriend** [comment]
The code of Tacotron-2 with Tensorflow has been synchronized [here](https://github.com/begeekmyfriend/Tacotron-2). Both of them support multi-speaker model. And the preprocessing is consistent with each other. You can extract the ground truth mel files on disk through [preprocess.py](https://github.com/begeekmyfriend/Tacotron-2/blob/mandarin-mel-prediction/preprocess.py) and then train them both on Torch and Tensorflow version.

**Comment by begeekmyfriend** [comment]
By the way the evaluation of multi-speaker model has been released in https://github.com/begeekmyfriend/tacotron2/issues/1

**Comment by nmfisher** [comment]
Yes, I understand that the code is compatible. My question was whether you have/will release the trained model weights that you used to create the evaluation samples?

**Comment by begeekmyfriend** [comment]
Sorry that the multi-speaker corpus is not public domain, it belongs to business. So I cannot release the pre-trained model. Sorry again about it.

**Comment by nmfisher** [comment]
OK, thanks!

**Comment by begeekmyfriend** [comment]
I beg your pardon that you might expand worker number of data loader for training acceleration https://github.com/begeekmyfriend/tacotron2/commit/35e7f455372707b3e7146ddda7bdb45f7de5daa5

**Comment by begeekmyfriend** [comment]
My fault https://github.com/begeekmyfriend/tacotron2/issues/5
