### ISSUE TITLE
error when inference

### ISSUE THREAD

**Issue by MorganCZY** [begeekmyfriend/tacotron2#20]
I did inference using command "bash scripts/griffin_lim_synth.sh" without activating amp_run. An error occured as shown in the following picture.
![image](https://user-images.githubusercontent.com/33675916/81253685-aef5f600-905b-11ea-8d52-acbe2f8584c8.png)
Here shows the content of griffin_lim_synth.sh.
![image](https://user-images.githubusercontent.com/33675916/81253763-e664a280-905b-11ea-8f28-2decaf7ec47b.png)

**Comment by begeekmyfriend** [comment]
You might change the [AMP operational level](https://github.com/begeekmyfriend/tacotron2/blob/master/inference.py#L77) and try again. By the way, what is the level during your [training](https://github.com/begeekmyfriend/tacotron2/blob/master/train.py#L254)?

**Comment by MorganCZY** [comment]
I have deleted all codes related to amp when training and inference. Because I can't install apex successfully.

**Comment by begeekmyfriend** [comment]
I have installed `apex` successfully. Please type such command according to the README of the repository.
```shell
$ pip install -v --no-cache-dir --global-option="--pyprof" --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by begeekmyfriend** [comment]
If it still fails then remove the `amp` option in `scripts/train_tacotron2.sh`.

**Comment by MorganCZY** [comment]
I did remove amp option in training and inference script. The scripts/griffin_lim_synth.sh and scripts/train_tacotron2.sh I ran are as follows.
![image](https://user-images.githubusercontent.com/33675916/81275545-6e5ea280-9084-11ea-9dab-a43e027019a2.png)
![image](https://user-images.githubusercontent.com/33675916/81275608-80404580-9084-11ea-97d8-837e1e982be8.png)
Some neccessary params for training have been written into train.py

**Comment by MorganCZY** [comment]
Btw, Apex can't be installed even strictly following the instructions in that repo's Readme.

**Comment by begeekmyfriend** [comment]
I see. Comment out those [lines](https://github.com/begeekmyfriend/tacotron2/blob/master/tacotron2/model.py#L274) to make all the parameters as type float32 please.

**Comment by MorganCZY** [comment]
You mean I should delete all four ".half()" ?

**Comment by begeekmyfriend** [comment]
Absolutely.

**Comment by MorganCZY** [comment]
The error is not solved. "RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2'" the same error with adding .half()

**Comment by begeekmyfriend** [comment]
Show me the type of `h0 c0 h1 c1` please.

**Comment by MorganCZY** [comment]
Deleting ".half()"  solves this error. I just made a mistake and I have deleted that comment.  Now , it shows the error as follows.
![image](https://user-images.githubusercontent.com/33675916/81277446-052c5e80-9087-11ea-8019-b7e68d5559f8.png)

**Comment by MorganCZY** [comment]
For only one speaker, the list "mels" here just contains one element. May I just remove torch.cat?

**Comment by begeekmyfriend** [comment]
Yes, you may try your own method.

**Comment by begeekmyfriend** [comment]
Show me the shape of `mels`.

**Comment by MorganCZY** [comment]
"mels" is a list, the length of which is decided by the lines in "text.txt". Each element in "mels" has a shape of [80, frames].

**Comment by MorganCZY** [comment]
Thus, Is it appropriate here to use torch.cat(mels, axis=-1)? Even not the grammer issue, concate all mels of all texts to a whole mel and send it to stft.inv_mel_spectrogram to synthesize one wav. Do I correctly understand your code logic?

**Comment by begeekmyfriend** [comment]
The code is all right for my test. You may try your own method as long as you can generate wav file.

**Comment by MorganCZY** [comment]
ok. Thank you for your reply and patience.
