### ISSUE TITLE
no mel-spectrogram saved in preprocessing stage

### ISSUE THREAD

**Issue by MorganCZY** [begeekmyfriend/tacotron2#21]
![image](https://user-images.githubusercontent.com/33675916/81264159-87ab2300-9073-11ea-8ff0-d9986d4cb7e5.png)
It seems you forget to save mel-spectrogram to the disk. Should I directly save "mel_spectrogram" or "mel_spectrogram.T"?

**Comment by begeekmyfriend** [comment]
This comment line would save your disk space and the ground truth Mel spectrograms are useless in training. You can generate GTA Mel spectrograms with `scripts/gta_synth.sh`.

**Comment by MorganCZY** [comment]
Why are the ground truth Mel spectrograms useless in training? Based on my understanding, tacotron2 is trained to learn a map between text sequence and mel. Can the training work if giving only texts but no corresponding the true mel?

**Comment by begeekmyfriend** [comment]
Sorry, I said wrong...The ground truth Mel spectrograms would be feed during [data loading](https://github.com/begeekmyfriend/tacotron2/blob/master/tacotron2/data_function.py#L69) in place. Therefore it no need to save as numpy files.

**Comment by MorganCZY** [comment]
I just checked codes about the class TextMelDataset. I now understand your design.
