### ISSUE TITLE
Solution about add more speakers midway.

### ISSUE THREAD

**Issue by leijue222** [begeekmyfriend/tacotron2#33]
Your base model already has four speakers. 

What will you do if you want to add the 5th speaker?
1. Retrain the model from scratch.
2. Based on the 4-speakers model, use  5th speaker data to train.

Solution 1: The drawback is that you have to start all over again every time, which is too time-consuming.
Solution 2: The number of speakers is related to the model's shape, so it will fail when reloading the base model.

Factors affecting model shape: the number of speakers and [characters](https://github.com/begeekmyfriend/tacotron2/blob/44b69e13af6560cfdda940b7c00af3431d22b7a5/tacotron2/text/symbols.py#L13).

Could you give me some advice about it?

**Comment by begeekmyfriend** [comment]
Absolutely it depends on the speaker number which duplicates the symbol tables. This model does not support fine tuning when you want to add some new speakers. By the way I have tried other solutions such as changing the word embedding related to different speakers. However the current solution is much more steady and running well. So I have no idea about your requirements.

**Comment by leijue222** [comment]
> By the way I have tried other solutions such as changing the word embedding related to different speakers.

Since English phones are all `uppercase letter + numbers` and Chinese phones are all `lowercase letters + numbers`, the phones are distinguishable. Therefore, I'm trying to add the LJSPECCH dataset as a new speaker to train from scratch.

> So I have no idea about your requirements.

The model can speak both English and Chinese words. 
And I want to try to record a few hours of my own voice data to train, to get the purpose of fine-tuning and adding speakers.

**Comment by begeekmyfriend** [comment]
Of course this model supports mixture of languages as long as it can distinguish different symbols that you design on your own. As for different tones from speakers it still a huge challenge to implement.

**Comment by leijue222** [comment]
Thanks for your help.

**Comment by leijue222** [comment]
> As for different tones from speakers is still a huge challenge to implement.

A compromise is to map the id of the new speaker to the existing speaker id. For example, there are speaker id (0, 1, 2) during training, and the id of the new speaker is set to one of (0, 1, 2) during finetune.

I have tried it; training 50 epochs with a small amount of data has good results.

> Of course this model supports mixture of languages as long as it can distinguish different symbols that you design on your own. 

I use [g2p](https://github.com/Kyubyong/g2p) to convert English to phoneme.
Maybe English data and Chinese data are not the same one speaker, the training result is bad. 
Or the matrix of English phonemes too sparse.

![align_0100_110300](https://user-images.githubusercontent.com/30276789/103048955-40a27b80-45cb-11eb-86b7-ede09b534341.png)

**Comment by leijue222** [comment]
Dataset: one speaker says two languages. This type of dataset is easy to train.
[Wav Samples](https://github.com/lturing/tacotronv2_wavernn_chinese/files/5763164/out.zip): _一共有A，B，C，D四个选项，请使用AI中的Computer vision技术自动选出正确答案。_
By the way, speakers have no influence on each other, right? Just separate and train with different data.
1. **Speaker 0:** `0.wav`
```
mels: [tensor([[-2.8765, -2.7719, -2.8387,  ..., -3.2160, -3.6020, -4.9893],
        [-3.2546, -3.1382, -3.1773,  ..., -3.3429, -3.6338, -5.0557],
        [-3.5550, -3.4103, -3.4107,  ..., -3.1448, -3.5457, -5.0250],
        ...,
        [-2.6870, -2.5213, -2.3601,  ..., -3.1760, -3.6523, -5.1519],
        [-2.6362, -2.4225, -2.2297,  ..., -3.1678, -3.6509, -5.1587],
        [-2.6244, -2.3537, -2.1523,  ..., -3.1202, -3.6275, -5.1621]])]
```
2. **Speaker 1:** `1.wav`
```
mels: [tensor([[-1.0986, -0.8132, -0.9845,  ..., -1.5600, -1.8979, -2.5278],
        [-0.9087, -0.5629, -0.8752,  ..., -1.2772, -1.8386, -2.4750],
        [-0.6838, -0.1870, -0.5341,  ..., -0.8729, -1.6136, -2.3331],
        ...,
        [-1.8976, -1.4484, -1.1838,  ..., -2.1380, -2.1383, -2.5169],
        [-1.7824, -1.2462, -0.9141,  ..., -2.1189, -2.0808, -2.4534],
        [-1.5541, -0.8552, -0.4252,  ..., -1.9931, -1.9561, -2.3472]])]
```
3. **Speaker 2:** `2.wav`

```
mels: [tensor([[-1.9335, -1.2416, -0.9765,  ..., -2.6344, -3.3166, -4.7619],
        [-1.7229, -0.5402, -0.0385,  ..., -2.5346, -3.2050, -4.7318],
        [-1.5512, -0.0778,  0.3828,  ..., -2.4392, -3.1485, -4.6993],
        ...,
        [-2.8530, -2.2040, -1.2443,  ..., -2.9496, -3.4969, -4.8711],
        [-2.8551, -2.1911, -1.2643,  ..., -2.9298, -3.4803, -4.8625],
        [-2.8779, -2.1691, -1.2487,  ..., -2.8952, -3.4552, -4.8605]])]
```
