### ISSUE TITLE
合成效果不佳

### ISSUE THREAD

**Issue by huhanpan** [begeekmyfriend/tacotron2#38]
我想问问，合成的效果不如[tensorflow版](https://github.com/begeekmyfriend/Tacotron-2)是因为啥原因，是因为multi-speaker的原因吗？
[sounds.zip](https://github.com/begeekmyfriend/tacotron2/files/6683679/sounds.zip)

**Comment by begeekmyfriend** [comment]
readme里面列举了vocoder，可以加上vocoder试试。如果你仅仅对比Tacotron部分的话，对比学习到的alignment是否更佳。最后说一句，我不再从事语音合成了。

**Comment by huhanpan** [comment]
谢谢你的回复，我自己去研究研究
