### ISSUE TITLE
segment a uttence

### ISSUE THREAD

**Issue by freecui** [begeekmyfriend/tacotron2#6]
is there any tool to segment a long uttence with aligning text on chinese?

**Comment by begeekmyfriend** [comment]
Add a punctuation such as comma among the pinyin transcript.

**Comment by freecui** [comment]
I don't have data with the pinyin transcript with a punctuation . I mean I want to use the long audios as traing data, but I just use short audios due to gpu memeory limit; so I want to segment audio with corresponding transcript, such as Montreal forced aligner

**Comment by begeekmyfriend** [comment]
As for audio clipping I suggest https://github.com/keithito/tacotron/issues/129. But the deficiency is that you need to match the transcript with the wav clip length rather than vise versa.

**Comment by freecui** [comment]
Is there any tool to add punctuation for a transcript

**Comment by begeekmyfriend** [comment]
```
bash scripts/griffin_lim_synth.sh
```
