### ISSUE TITLE
audio preprocessing for wavernn

### ISSUE THREAD

**Issue by violet-duck** [begeekmyfriend/tacotron2#8]
Hi, @begeekmyfriend I would like to know how did you do the preprocessing for wavernn since I didn't find the preprocess scripts in the repo. 
Also, to my understanding, this taco2 is compatible with your wavernn as I set vocoder=wavernn, is that correct?
thxxxxxxx

**Comment by begeekmyfriend** [comment]
Yes, I have illustrated it https://github.com/begeekmyfriend/tacotron2/issues/4#issuecomment-564924780

**Comment by violet-duck** [comment]
Got it. So do I have to use --gta or I can use mel and quant dirs instand? Is there any difference between  using gta and mel for wavernn training?

**Comment by begeekmyfriend** [comment]
GTA is the evaluation from training data while mel (ground truth) is the true training data. I recommand you using GTA.

**Comment by violet-duck** [comment]
Thank you for your explanation
